services:
  - type: web
    name: igp-dashboard-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn igp_dashboard.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: igp-dashboard-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: "igp-dashboard-web.onrender.com"
      - key: REDIS_URL
        value: ""
databases:
  - name: igp-dashboard-db
    plan: free
